#!/bin/bash
pushd build
cmake -DARMV6A=ON \
	-DFREEPLAYTECH_WAVESHARE32B=ON \
	-DSPI_BUS_CLOCK_DIVISOR=6 \
	-DDISPLAY_BREAK_ASPECT_RATIO_WHEN_SCALING=ON \
	-DUSE_DMA_TRANSFERS=ON \
	-DDMA_TX_CHANNEL=4 \
	-DDMA_RX_CHANNEL=2 \
	-DSINGLE_CORE_BOARD=ON \
	-DSTATISTICS= \
	..

make -j
popd
